
version: '3.8'

services:
  frontend:
    container_name: frontend
    # image: harishuptodate/deals24-frontend:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3000/api
        - VITE_ADMIN_USERNAME=${VITE_ADMIN_USERNAME}
        - VITE_ADMIN_PASSWORD=${VITE_ADMIN_PASSWORD} 
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000/api} # if value is given here, this is the final value it considers, if not given here, it takes from .env file
    networks:
      - deals24-network

  backend:
    container_name: backend
    # image: harishuptodate/deals24-backend:v1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - WEBHOOK_URL=https://fbc4-106-222-555-41.ngrok-free.app
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - IS_SALE_MODE=${IS_SALE_MODE:-false}
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - deals24-network
    restart: unless-stopped


networks:
  deals24-network:
    driver: bridge
